export const metadata = {
    title: "hello",
    description: "Generated by Next.js",
  };
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode,
  }) {
    return (
      <html lang="en">
        <body>
            <main className="flex p-4">{children}</main>
        </body>
      </html>
    );
  }